/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import networking.Client;
import networking.Command;
import org.json.JSONArray;
import org.json.JSONObject;
import school.GiaoVien;
import school.Student;
import school.loaiDiem;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame {
    
    private Client client;
    private boolean isGV = false;
    private List<Student> studentList;
    private Student tempStudent;
    private GiaoVien gvChuNhiem;
    private JSONArray universalJsonArray;
     
    /**
     * Creates new form Main
     */
    public Main() {
        client = new Client();
        client.startConnection();
       
        initComponents();
        loginPanel.setVisible(true);
        loginFailed_LB.setVisible(false);
        jMenuBar1.setVisible(false);
        mainMenuPanel.setVisible(false);
        xemDanhSachLopPanel.setVisible(false);
        xemBangDiemPanel.setVisible(false);
        nhapDiemPanel.setVisible(false);
        
        capNhatDiem_jMenu4.setVisible(false);
        
        //Lay tat ca nam hoc tu CSDL de them vao combo box?
        client.sendCommand(Command.GET_NAM_HOC);
        if (client.readMessage().equals(Command.FALSE.name())) {
            System.out.println("Unable to get NamHoc");
        } 
        else {
            //Receive the JSON array and process it
            universalJsonArray = client.receiveNamHocArray();
            
            for (int i = 0; i < universalJsonArray.length(); i++) {
                namHoc_CB.addItem(universalJsonArray.getJSONObject(i).getString("NamHoc"));
            }
        }
        
        //Khoi tai combox loai diem
        loaiDiem_CB.addItem(new loaiDiem("Điểm miệng", "Mieng").toString());
        loaiDiem_CB.addItem(new loaiDiem("15 Phút", "15Phut").toString());
        loaiDiem_CB.addItem(new loaiDiem("1 Tiết", "1Tiet").toString());
        loaiDiem_CB.addItem(new loaiDiem("Giữa kỳ", "GiuaKy").toString());
        loaiDiem_CB.addItem(new loaiDiem("Cuối kỳ", "CuoiKy").toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tenNgDung_LB = new javax.swing.JLabel();
        matKhau_LB = new javax.swing.JLabel();
        tenNgDung_TF = new javax.swing.JTextField();
        matKhau_PF = new javax.swing.JPasswordField();
        login_BTN = new javax.swing.JButton();
        clear_BTN = new javax.swing.JButton();
        loginFailed_LB = new javax.swing.JLabel();
        mainMenuPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        xemDanhSachLopPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        maLop_LB = new javax.swing.JLabel();
        xemDSLop_BTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        maLop_TF = new javax.swing.JTextField();
        maGV_TF = new javax.swing.JTextField();
        hoTenGV_TF = new javax.swing.JTextField();
        namSinhGV_TF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        maLopFailed_TF = new javax.swing.JTextField();
        gioiTinhGV_TF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsLop_Table = new javax.swing.JTable();
        xemBangDiemPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangDiem_Table = new javax.swing.JTable();
        bangDiemMaHS_TF = new javax.swing.JTextField();
        bangDiemMaHS_LB = new javax.swing.JLabel();
        xemBangDiem_BTN = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        hocKy_CB = new javax.swing.JComboBox<>();
        namHoc_CB = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        nhapDiemPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        maLop_nhapDiemPanel = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        luuDiem_TB = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        loaiDiem_CB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        trangChu_jMenu1 = new javax.swing.JMenu();
        dsLop_jMenu2 = new javax.swing.JMenu();
        xemBangDiem_jMenu3 = new javax.swing.JMenu();
        capNhatDiem_jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tenNgDung_LB.setText("Tên người dùng");

        matKhau_LB.setText("Mật khẩu");

        matKhau_PF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matKhau_PFActionPerformed(evt);
            }
        });

        login_BTN.setText("Đăng nhập");
        login_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_BTNActionPerformed(evt);
            }
        });

        clear_BTN.setText("Xóa");
        clear_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_BTNActionPerformed(evt);
            }
        });

        loginFailed_LB.setForeground(new java.awt.Color(255, 0, 0));
        loginFailed_LB.setText("Tên người dùng hoặc mật khẩu không đúng!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(login_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(clear_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginFailed_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tenNgDung_LB)
                        .addGap(64, 64, 64)
                        .addComponent(tenNgDung_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(matKhau_LB)
                        .addGap(99, 99, 99)
                        .addComponent(matKhau_PF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenNgDung_LB)
                    .addComponent(tenNgDung_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matKhau_PF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matKhau_LB))
                .addGap(18, 18, 18)
                .addComponent(loginFailed_LB)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_BTN)
                    .addComponent(login_BTN))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setText("ỨNG DỤNG QUẢN LÝ ĐIỂM HỌC SINH THPT");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Người thực hiện:");

        jLabel3.setText("Trần Lê Phước An ");

        jLabel4.setText("Lý Minh Trí");

        jLabel5.setText("Nguyễn Hoài An");

        jLabel11.setText("Niên luận ngành kỹ thuật phần mềm");

        jLabel12.setText("Giảng viên hướng dẫn:");

        jLabel13.setText("Ths. Ông Thị Mỹ Linh");

        jLabel14.setText("B2003879");

        jLabel15.setText("B2003931");

        jLabel16.setText("B2012057");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel14)))))
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16))
                .addGap(49, 49, 49)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("(Build 1.0)");

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        maLop_LB.setText("Mã lớp:");

        xemDSLop_BTN.setText("Xem danh sách lớp");
        xemDSLop_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemDSLop_BTNActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã giáo viên:");

        jLabel8.setText("Họ tên:");

        jLabel9.setText("Năm sinh:");

        jLabel10.setText("Giới tính:");

        maGV_TF.setEditable(false);

        hoTenGV_TF.setEditable(false);

        namSinhGV_TF.setEditable(false);

        jLabel19.setText("Giáo viên chủ nhiệm:");

        maLopFailed_TF.setEditable(false);
        maLopFailed_TF.setForeground(new java.awt.Color(255, 0, 0));
        maLopFailed_TF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        gioiTinhGV_TF.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(maLopFailed_TF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maGV_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(maLop_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maLop_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xemDSLop_BTN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoTenGV_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namSinhGV_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gioiTinhGV_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maLop_LB)
                    .addComponent(maLop_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xemDSLop_BTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maLopFailed_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(maGV_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(hoTenGV_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(namSinhGV_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(gioiTinhGV_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dsLop_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã học sinh", "Họ tên", "Năm sinh", "Giới tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dsLop_Table);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout xemDanhSachLopPanelLayout = new javax.swing.GroupLayout(xemDanhSachLopPanel);
        xemDanhSachLopPanel.setLayout(xemDanhSachLopPanelLayout);
        xemDanhSachLopPanelLayout.setHorizontalGroup(
            xemDanhSachLopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemDanhSachLopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(xemDanhSachLopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(xemDanhSachLopPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        xemDanhSachLopPanelLayout.setVerticalGroup(
            xemDanhSachLopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xemDanhSachLopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(xemDanhSachLopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemDanhSachLopPanelLayout.createSequentialGroup()
                    .addContainerGap(165, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bangDiem_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên môn", "Điểm miệng", "15 Phút", "1 Tiết", "Giữa kỳ", "Cuối kỳ", "Trung bình môn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bangDiem_Table);

        bangDiemMaHS_LB.setText("Nhập mã học sinh:");

        xemBangDiem_BTN.setText("Xem");
        xemBangDiem_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemBangDiem_BTNActionPerformed(evt);
            }
        });

        jLabel17.setText("Năm học:");

        jLabel18.setText("Học kỳ");

        hocKy_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        namHoc_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namHoc_CBActionPerformed(evt);
            }
        });

        jLabel20.setText("Họ và tên:");

        jTextField1.setEditable(false);

        jLabel21.setText("Hạnh kiểm:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bangDiemMaHS_LB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bangDiemMaHS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namHoc_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hocKy_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xemBangDiem_BTN))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bangDiemMaHS_LB)
                    .addComponent(bangDiemMaHS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(namHoc_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(hocKy_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xemBangDiem_BTN))
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout xemBangDiemPanelLayout = new javax.swing.GroupLayout(xemBangDiemPanel);
        xemBangDiemPanel.setLayout(xemBangDiemPanelLayout);
        xemBangDiemPanelLayout.setHorizontalGroup(
            xemBangDiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xemBangDiemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        xemBangDiemPanelLayout.setVerticalGroup(
            xemBangDiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xemBangDiemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel22.setText("Mã lớp:");

        jLabel23.setText("Năm học: 2022-2023");

        jLabel24.setText("Học kỳ 1");

        jLabel25.setText("Môn học:");

        luuDiem_TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Họ tên", ""
            }
        ));
        jScrollPane3.setViewportView(luuDiem_TB);

        jLabel26.setText("Loại điểm:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lưu");

        javax.swing.GroupLayout nhapDiemPanelLayout = new javax.swing.GroupLayout(nhapDiemPanel);
        nhapDiemPanel.setLayout(nhapDiemPanelLayout);
        nhapDiemPanelLayout.setHorizontalGroup(
            nhapDiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhapDiemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhapDiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nhapDiemPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maLop_nhapDiemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loaiDiem_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        nhapDiemPanelLayout.setVerticalGroup(
            nhapDiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhapDiemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhapDiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(maLop_nhapDiemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(loaiDiem_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        trangChu_jMenu1.setText("Trang chủ");
        trangChu_jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangChu_jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(trangChu_jMenu1);

        dsLop_jMenu2.setText("Xem danh sách lớp");
        dsLop_jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsLop_jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(dsLop_jMenu2);

        xemBangDiem_jMenu3.setText("Xem bảng điểm");
        xemBangDiem_jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xemBangDiem_jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(xemBangDiem_jMenu3);

        capNhatDiem_jMenu4.setText("Cập nhật điểm");
        capNhatDiem_jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capNhatDiem_jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(capNhatDiem_jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xemDanhSachLopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xemBangDiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(nhapDiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xemDanhSachLopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xemBangDiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(nhapDiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean login(String userName, String password) {
        boolean success = false;
        
        if (!password.isEmpty() && !userName.isEmpty())  {
            client.sendCommand(Command.LOGIN);
            client.sendMessage(userName);
            client.sendMessage(password);
            
            //Read message to see if login is success
            String msg = client.readMessage();
            
            if (msg.equals(Command.TRUE.name())) {
                success = true;
            } else {
                success = false;
            }
        }
        
        return success;
    }
    private void login_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_BTNActionPerformed
        // TODO add your handling code here:
        String userName = tenNgDung_TF.getText();
        String password = new String(matKhau_PF.getPassword());
        
        if (login(userName, password)) {
            //Go to main menu
            mainMenuPanel.setVisible(true);
            loginFailed_LB.setVisible(false);
            loginPanel.setVisible(false);
            jMenuBar1.setVisible(true);
            
            if (userName.charAt(0) == 'G' && userName.charAt(1) == 'V') {
                System.out.println("GV login");
                isGV = true;
                capNhatDiem_jMenu4.setVisible(true);
            }
            System.out.println("Login success");
        } else {
            System.out.println("Login failed");
            loginFailed_LB.setVisible(true);
        }
    }//GEN-LAST:event_login_BTNActionPerformed

    private void matKhau_PFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matKhau_PFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matKhau_PFActionPerformed

    private void clear_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_BTNActionPerformed
        // TODO add your handling code here:
        tenNgDung_TF.setText("");
        matKhau_PF.setText("");
    }//GEN-LAST:event_clear_BTNActionPerformed

    private void trangChu_jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangChu_jMenu1MouseClicked
        // TODO add your handling code here:
        mainMenuPanel.setVisible(true);
        
        xemDanhSachLopPanel.setVisible(false);
        xemBangDiemPanel.setVisible(false);
    }//GEN-LAST:event_trangChu_jMenu1MouseClicked

    private void dsLop_jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsLop_jMenu2MouseClicked
        // TODO add your handling code here:
        xemDanhSachLopPanel.setVisible(true);

        mainMenuPanel.setVisible(false);        
        xemBangDiemPanel.setVisible(false);
    }//GEN-LAST:event_dsLop_jMenu2MouseClicked

    private void xemBangDiem_jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xemBangDiem_jMenu3MouseClicked
        // TODO add your handling code here:
        xemBangDiemPanel.setVisible(true);
        
        mainMenuPanel.setVisible(false);
        xemDanhSachLopPanel.setVisible(false);
    }//GEN-LAST:event_xemBangDiem_jMenu3MouseClicked
    
    public void viewDanhSachLop() {
        this.studentList = client.getStudentList();
        
        if (studentList.isEmpty()) {
            System.out.println("Student list is emtpy, table cant be created");
        } else {
            DefaultTableModel dsLopTable = (DefaultTableModel) (this.dsLop_Table.getModel());
            dsLopTable.setRowCount(0);
            int n = 1;
            
            for (Student x : studentList) {
                dsLopTable.addRow(new Object[]{n, x.getMaHS(), x.getHoTen(), x.getNamSinh(), x.getGioiTInh()});
                n++;
            }
        }
        //this.studentList.clear();
        client.clearStudentlist();
    }
    
    public void getClassInfo(String classID) {
        //Send get class info command
        client.sendCommand(Command.GET_CLASS_INFO);
        
        //Send the ID to query
        client.sendMessage(classID);
        
        //Read the boolean to see if classID exist
        if (client.readMessage().equals(Command.TRUE.name())) {
            //Receive the data for the class
            client.receiveStudentJSONArray();
            
            //Receive GV chu nhiem for the class
            client.receiveGVChuNhiem();
            
            //Display the table ds lop
            viewDanhSachLop();
            
            //Display GV chu nhiem info for class
            gvChuNhiem = client.getGvChuNhiem();
            maGV_TF.setText(gvChuNhiem.getMaGV());
            hoTenGV_TF.setText(gvChuNhiem.getHoTen());
            namSinhGV_TF.setText(Integer.toString(gvChuNhiem.getNamSinh()));
            gioiTinhGV_TF.setText(gvChuNhiem.getGioiTinh());
        }
        else {
            maLopFailed_TF.setText("Mã lớp sai hoặc lớp học không tồn tại.");
            System.out.println("Incorrect Class ID");
        }        
    }
    
    private void xemDSLop_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemDSLop_BTNActionPerformed
        // TODO add your handling code here:
        String classID =maLop_TF.getText();
        
        if (!classID.isEmpty()) {
            getClassInfo(classID);
        }     
    }//GEN-LAST:event_xemDSLop_BTNActionPerformed
    
    public void viewBangDiem() {
        DefaultTableModel bangDiem = (DefaultTableModel) (this.bangDiem_Table.getModel());
        bangDiem.setRowCount(0);
        
        float diemMieng; 
        float diem15Phut;
        float diem1Tiet;
        float giuaKy;
        float cuoiKy;
        float diemTB;
        
        for (int i = 0; i < universalJsonArray.length(); i++) {
            String TenMon = universalJsonArray.getJSONObject(i).getString("TenMon");
            diemMieng = universalJsonArray.getJSONObject(i).getFloat("Mieng");
            diem15Phut = universalJsonArray.getJSONObject(i).getFloat("15Phut");
            diem1Tiet  = universalJsonArray.getJSONObject(i).getFloat("1Tiet");
            giuaKy = universalJsonArray.getJSONObject(i).getFloat("GiuaKy");
            cuoiKy = universalJsonArray.getJSONObject(i).getFloat("CuoiKy");
            diemTB = universalJsonArray.getJSONObject(i).getFloat("DiemTB");
            bangDiem.addRow(new Object[]{i+1, TenMon, diemMieng, diem15Phut, diem1Tiet, giuaKy, cuoiKy, diemTB});
        }
    }
    
    private void xemBangDiem_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemBangDiem_BTNActionPerformed
        // TODO add your handling code here:
        JSONObject bangDiemInfo = new JSONObject();
        String jsonString;
        
        client.sendCommand(Command.GET_BANG_DIEM);
        
        if (!bangDiemMaHS_TF.getText().isEmpty()) {
            bangDiemInfo.put("MaHS", bangDiemMaHS_TF.getText());
            bangDiemInfo.put("NamHoc", namHoc_CB.getSelectedItem());
            bangDiemInfo.put("HocKy", hocKy_CB.getSelectedItem());
            
            jsonString = bangDiemInfo.toString();
            
            client.sendMessage(jsonString);
            
            if (client.readMessage().equals(Command.TRUE.name())) {
                universalJsonArray = client.receiveBangDiemArray();
                viewBangDiem();
                //System.out.println(universalJsonArray);
            }
            else {
                System.out.println("Ma hoc sinh khong ton tai!!!");
            }
            
        } else {
            System.out.println("MaHS khong duoc de trong!");
        }
        
    }//GEN-LAST:event_xemBangDiem_BTNActionPerformed

    private void namHoc_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namHoc_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namHoc_CBActionPerformed

    private void capNhatDiem_jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capNhatDiem_jMenu4MouseClicked
        // TODO add your handling code here:
        nhapDiemPanel.setVisible(true);
        
        mainMenuPanel.setVisible(false);
        xemBangDiemPanel.setVisible(false);
        xemDanhSachLopPanel.setVisible(false);
    }//GEN-LAST:event_capNhatDiem_jMenu4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Nhấn vao sẽ cập nhật bảng danh sách lớp
        Object item = loaiDiem_CB.getSelectedItem();
        String loaiDiem = item.toString();
        
        System.out.println(loaiDiem);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bangDiemMaHS_LB;
    private javax.swing.JTextField bangDiemMaHS_TF;
    private javax.swing.JTable bangDiem_Table;
    private javax.swing.JMenu capNhatDiem_jMenu4;
    private javax.swing.JButton clear_BTN;
    private javax.swing.JTable dsLop_Table;
    private javax.swing.JMenu dsLop_jMenu2;
    private javax.swing.JTextField gioiTinhGV_TF;
    private javax.swing.JTextField hoTenGV_TF;
    private javax.swing.JComboBox<String> hocKy_CB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> loaiDiem_CB;
    private javax.swing.JLabel loginFailed_LB;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton login_BTN;
    private javax.swing.JTable luuDiem_TB;
    private javax.swing.JTextField maGV_TF;
    private javax.swing.JTextField maLopFailed_TF;
    private javax.swing.JLabel maLop_LB;
    private javax.swing.JTextField maLop_TF;
    private javax.swing.JTextField maLop_nhapDiemPanel;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel matKhau_LB;
    private javax.swing.JPasswordField matKhau_PF;
    private javax.swing.JComboBox<String> namHoc_CB;
    private javax.swing.JTextField namSinhGV_TF;
    private javax.swing.JPanel nhapDiemPanel;
    private javax.swing.JLabel tenNgDung_LB;
    private javax.swing.JTextField tenNgDung_TF;
    private javax.swing.JMenu trangChu_jMenu1;
    private javax.swing.JPanel xemBangDiemPanel;
    private javax.swing.JButton xemBangDiem_BTN;
    private javax.swing.JMenu xemBangDiem_jMenu3;
    private javax.swing.JButton xemDSLop_BTN;
    private javax.swing.JPanel xemDanhSachLopPanel;
    // End of variables declaration//GEN-END:variables
}
